// Copyright 2016, University of Colorado Boulder

/**
 * Possible locations of the balloon in Balloons and Static Electricity, mapped.
 * @author Jesse Greenberg
 */
define( function( require ) {
  'use strict';

  var BalloonLocationEnum = {
    TOP_RIGHT: 'TOP_RIGHT',
    UPPER_WALL: 'UPPER_WALL',
    LOWER_WALL: 'LOWER_WALL',
    BOTTOM_WALL: 'BOTTOM_WALL',
    TOP_RIGHT_PLAY_AREA: 'TOP_RIGHT_PLAY_AREA',
    UPPER_RIGHT_PLAY_AREA: 'UPPER_RIGHT_PLAY_AREA',
    LOWER_RIGHT_PLAY_AREA: 'LOWER_RIGHT_PLAY_AREA',
    BOTTOM_RIGHT_PLAY_AREA: 'BOTTOM_RIGHT_PLAY_AREA',
    TOP_CENTER_PLAY_AREA: 'TOP_CENTER_PLAY_AREA',
    UPPER_CENTER_PLAY_AREA: 'UPPER_CENTER_PLAY_AREA',
    LOWER_CENTER_PLAY_AREA: 'LOWER_CENTER_PLAY_AREA',
    BOTTOM_CENTER_PLAY_AREA: 'BOTTOM_CENTER_PLAY_AREA',
    TOP_LEFT_PLAY_AREA: 'TOP_LEFT_PLAY_AREA',
    UPPER_LEFT_PLAY_AREA: 'UPPER_LEFT_PLAY_AREA',
    LOWER_LEFT_PLAY_AREA: 'LOWER_LEFT_PLAY_AREA',
    BOTTOM_LEFT_PLAY_AREA: 'BOTTOM_LEFT_PLAY_AREA',
    TOP_RIGHT_ARM: 'TOP_RIGHT_ARM',
    UPPER_RIGHT_ARM: 'UPPER_RIGHT_ARM',
    LOWER_RIGHT_ARM: 'LOWER_RIGHT_ARM',
    BOTTOM_RIGHT_ARM: 'BOTTOM_RIGHT_ARM',
    TOP_RIGHT_SWEATER: 'TOP_RIGHT_SWEATER',
    UPPER_RIGHT_SWEATER: 'UPPER_RIGHT_SWEATER',
    LOWER_RIGHT_SWEATER: 'LOWER_RIGHT_SWEATER',
    BOTTOM_RIGHT_SWEATER: 'BOTTOM_RIGHT_SWEATER',
    TOP_LEFT_SWEATER: 'TOP_LEFT_SWEATER',
    UPPER_LEFT: 'UPPER_LEFT_SWEATER',
    LOWER_LEFT_SWEATER: 'LOWER_LEFT_SWEATER',
    BOTTOM_LEFT_SWEATER: 'BOTTOM_LEFT_SWEATER',
    TOP_LEFT_ARM: 'TOP_LEFT_ARM',
    UPPER_LEFT_ARM: 'UPPER_LEFT_ARM',
    LOWER_LEFT_ARM: 'LOWER_LEFT_ARM',
    BOTTOM_LEFT_ARM: 'BOTTOM_LEFT_ARM',
    BOTTOM_LEFT: 'BOTTOM_LEFT',
    LOWER_LEFT: 'LOWER_LEFT',
    UPPER_LEFT: 'UPPER_LEFT',
    TOP_LEFT:'TOP_LEFT'
  };

  // verify that enum is immutable, without the runtime penalty in production code
  if ( assert ) { Object.freeze( BalloonLocationEnum ); }

  return BalloonLocationEnum;
} );